<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\ItemUom;
use App\Models\ItemBrand;
use App\Models\PersonnelItem;
use App\Models\ItemCategory;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\ItemsExport;
use Illuminate\Http\Request;

use Barryvdh\DomPDF\Facade\Pdf;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $query = $request->get('search', '');
        $remarkFilter = $request->get('remark');
        $categoryId = $request->get('category');
        $brandId = $request->get('brand');

        $item_categories = ItemCategory::all();
        $item_brands = ItemBrand::all();
        $item_uoms = ItemUom::all();

        $itemCount = Item::count();

        // Base query for items
        $itemsQuery = Item::query();

        if ($query) {
            $itemsQuery->where(function ($q) use ($query) {
                $q->where('item_name', 'like', "%$query%")
                    ->orWhere('item_serialno', 'like', "%$query%");
            });
        }

        if ($remarkFilter) {
            $itemsQuery->where('item_remark', $remarkFilter);
        }

        if ($categoryId) {
            $itemsQuery->where('item_category_id', $categoryId);
        }

        if ($brandId) {
            $itemsQuery->where('item_brand_id', $brandId);
        }

        // Get regular items (eager-load for PDF / table display)
        $items = $itemsQuery->with(['category', 'uom'])->orderBy('updated_at', 'desc')->get();

        // Paginate manually (using the collection of regular items)
        $perPage = 20;
        $page = $request->get('page', 1);
        $itemsPaginated = new \Illuminate\Pagination\LengthAwarePaginator(
            $items->forPage($page, $perPage),
            $items->count(),
            $perPage,
            $page,
            ['path' => $request->url(), 'query' => $request->query()]
        );

        $itemsPaginated->appends([
            'search' => $query,
            'remark' => $remarkFilter,
            'category' => $categoryId,
            'brand' => $brandId
        ]);

        // Get unique remarks for dropdown (only from the Item table now)
        $item_remarks = Item::select('item_remark')
            ->distinct()
            ->orderBy('item_remark')
            ->pluck('item_remark')
            ->toArray();

        // EXPORT SINGLE ITEM PDF
        if ($request->get('export') == 'pdf' && $request->has('item_id')) {
            $itemId = $request->get('item_id');
            $item = Item::findOrFail($itemId);
            $pdf = Pdf::loadView('inventory.pdf-individual', compact('item'));
            return $pdf->stream("item_{$item->item_id}.pdf");
        }

        // EXPORT LIST PDF (all rows matching filters, or only selected ids)
        if ($request->get('export') == 'pdf' && !$request->has('item_id')) {
            $ids = $request->get('ids');

            if ($ids) {
                $idArray = array_filter(explode(',', $ids));
                $pdfItems = Item::with(['category', 'uom'])
                    ->whereIn('item_id', $idArray)
                    ->get();
            } else {
                $pdfItems = $items;
            }

            // 🔥 SORT FOR PDF: Group by Category
            $pdfItems = $pdfItems->sortBy('category.item_category_name', SORT_NATURAL | SORT_FLAG_CASE)->values();

            // Load view and set Landscape
            $pdf = Pdf::loadView('inventory.pdf-forall', ['allItems' => $pdfItems])
                ->setPaper('a4', 'landscape');

            // Render PDF to initialize canvas
            $pdf->render();
            $canvas = $pdf->getDomPDF()->getCanvas();

            // Script for Footer and Page Numbers
            $script = <<<'EOT'
            $font = $fontMetrics->get_font("Helvetica", "normal");
            $size = 10;

            if ($PAGE_NUM === $PAGE_COUNT) {
                $footerText = "Generated by Goldtown Inventory System " . date('F d, Y');
                $footerWidth = $fontMetrics->getTextWidth($footerText, $font, $size);
                $xFooter = ($pdf->get_width() - $footerWidth) / 2;
                $yFooter = $pdf->get_height() - (2.5 * 12);
                $pdf->text($xFooter, $yFooter, $footerText, $font, $size);
            }

            // Page number at bottom-right
            $pageText = "Page " . $PAGE_NUM;
            $pageWidth = $fontMetrics->getTextWidth($pageText, $font, $size);
            $xPage = $pdf->get_width() - $pageWidth - (2 * 12);
            $yPage = $pdf->get_height() - (2.5 * 12);
            $pdf->text($xPage, $yPage, $pageText, $font, $size);
EOT;
            $canvas->page_script($script);

            return $pdf->stream('inventory.pdf');
        }

        // AJAX Table Update
        if ($request->ajax()) {
            return response()->json([
                'table' => view('inventory.inventory-table', [
                    'items' => $itemsPaginated,
                    'item_categories' => $item_categories,
                    'item_brands' => $item_brands,
                    'item_uoms' => $item_uoms,
                ])->render(),
            ]);
        }

        // EXPORT EXCEL
        if ($request->get('export') == 'excel') {
            $ids = $request->get('ids');
            $dbQuery = Item::with(['category', 'uom', 'brand']); // Ensure eager loading

            if ($ids) {
                $idArray = explode(',', $ids);
                $dbQuery->whereIn('item_id', $idArray);
            } else {
                if ($query) {
                    $dbQuery->where(function ($q) use ($query) {
                        $q->where('item_name', 'like', "%$query%")
                            ->orWhere('item_serialno', 'like', "%$query%");
                    });
                }
                if ($remarkFilter) {
                    $dbQuery->where('item_remark', $remarkFilter);
                }
                if ($categoryId) {
                    $dbQuery->where('item_category_id', $categoryId);
                }
                if ($brandId) {
                    $dbQuery->where('item_brand_id', $brandId);
                }
            }

            // 🔥 SORT FOR EXCEL: Group by Category
            $filteredItems = $dbQuery->get()->sortBy('category.item_category_name', SORT_NATURAL | SORT_FLAG_CASE)->values();

            return Excel::download(new ItemsExport($filteredItems), 'Item Inventory Report.xlsx');
        }

        return view('inventory.index', [
            'items' => $itemsPaginated,
            'item_categories' => $item_categories,
            'item_brands' => $item_brands,
            'item_uoms' => $item_uoms,
            'item_remarks' => $item_remarks,
            'itemCount' => $itemCount
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $itemQuantityRules = ['required', 'integer'];
        if ($request->filled('item_serialno')) {
            $itemQuantityRules[] = 'min:1';
            $itemQuantityRules[] = 'max:1';
        } else {
            $itemQuantityRules[] = 'min:0';
            $itemQuantityRules[] = 'max:999999';
        }

        // 1. Validation
        $request->validate([
            'item_name' => 'nullable|string|max:255',
            'item_serialno' => 'nullable|string|max:255',
            'item_quantity' => $itemQuantityRules,
            'item_remark' => 'nullable|string|max:255',
            'item_uom_name' => 'required|string|max:255',
            'item_brand_name' => 'nullable|string|max:255',
            'item_category_id' => 'required|exists:item_categories,item_category_id'
        ]);

        // 2. Resolve Brand and UOM early
        $brandId = null;
        if ($request->filled('item_brand_name')) {
            $brand = ItemBrand::firstOrCreate(['item_brand_name' => $request->item_brand_name]);
            $brandId = $brand->item_brand_id;
        }
        $uom = ItemUom::firstOrCreate(['item_uom_name' => $request->item_uom_name]);

        // 3. Resolve Name Logic
        $category = ItemCategory::findOrFail($request->item_category_id);
        $baseName = $category->item_category_name;

        if (!$request->filled('item_name')) {
            $lastItem = Item::where('item_category_id', $category->item_category_id)
                ->where('item_name', 'like', $baseName . ' %')
                ->orderBy('item_name', 'desc')
                ->first();

            if ($lastItem) {
                preg_match('/(\d+)$/', $lastItem->item_name, $matches);
                $nextNumber = isset($matches[1]) ? (int) $matches[1] + 1 : 1;
            } else {
                $nextNumber = 1;
            }
            $finalName = $baseName . ' ' . str_pad($nextNumber, 3, '0', STR_PAD_LEFT);
        } else {
            $finalName = $request->item_name;
        }

        // 4. DUPLICATE & MERGE LOGIC (Updated to include Item Status/Remark)
        // Now we check for Name + Brand + Serial + Remark
        $existingItem = Item::where('item_name', $finalName)
            ->where('item_brand_id', $brandId)
            ->where('item_serialno', $request->item_serialno)
            ->where('item_remark', $request->item_remark) // 🔥 This separates them by status
            ->first();

        if ($existingItem) {
            $existingItem->item_quantity += $request->item_quantity;
            $existingItem->item_quantity_remaining += $request->item_quantity;

            // Recalculate Stock Status (Available, Low, Out)
            if ($existingItem->item_quantity_remaining <= 0) {
                $existingItem->item_quantity_status = 'Out of Stock';
            } elseif ($existingItem->item_quantity_remaining < ($existingItem->item_quantity * 0.2)) {
                $existingItem->item_quantity_status = 'Low Stock';
            } else {
                $existingItem->item_quantity_status = 'Available';
            }

            $existingItem->touch(); // Move to top of list
            $existingItem->save();

            return response()->json([
                'success' => true,
                'message' => "Item quantities merged for status: {$request->item_remark}",
                'data' => $existingItem
            ]);
        }

        // 5. SERIAL UNIQUE CHECK (Only for NEW items)
        if ($request->filled('item_serialno')) {
            $serialExists = Item::where('item_serialno', $request->item_serialno)->exists();
            if ($serialExists) {
                return response()->json([
                    'success' => false,
                    'message' => "The serial number '{$request->item_serialno}' is already registered."
                ], 422);
            }
        }

        // 6. Create New Item
        $quantityStatus = $request->item_quantity > 0 ? 'Available' : 'Out of Stock';

        $item = Item::create([
            'item_name' => $finalName,
            'item_serialno' => $request->item_serialno,
            'item_quantity' => $request->item_quantity,
            'item_quantity_remaining' => $request->item_quantity,
            'item_quantity_status' => $quantityStatus,
            'item_remark' => $request->item_remark,
            'item_category_id' => $request->item_category_id,
            'item_uom_id' => $uom->item_uom_id,
            'item_brand_id' => $brandId,
        ]);

        return response()->json([
            'success' => true,
            'message' => 'New item added successfully',
            'data' => $item
        ]);
    }

    public function storeCategory(Request $request)
    {
        $request->validate([
            'item_category_name' => 'required|string|max:255|unique:item_categories,item_category_name',
            'item_category_icon' => 'nullable|string|max:255'
        ]);

        $category = ItemCategory::create([
            'item_category_name' => $request->item_category_name,
            'item_category_icon' => $request->item_category_icon
        ]);

        // ✅ RETURN JSON INSTEAD OF REDIRECT
        return response()->json([
            'item_category_id' => $category->item_category_id,
            'item_category_name' => $category->item_category_name,
            'item_category_icon' => $category->item_category_icon
        ]);
    }
    /**
     * Display the specified resource.
     */
    public function show(Item $item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Item $item)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $item_id)
    {
        $item = Item::findOrFail($item_id);

        $itemQuantityRules = ['required', 'integer', 'min:0'];
        if ($request->filled('item_serialno')) {
            $itemQuantityRules[] = 'max:1';
        }

        // Validate input
        $request->validate([
            'item_name' => 'required|string|max:255',
            'item_serialno' => 'nullable|string|max:255',
            'item_quantity' => $itemQuantityRules,
            'item_remark' => 'nullable|string|max:500',
            'item_brand_name' => 'nullable|string|max:255',
            'item_uom_name' => 'nullable|string|max:255',
        ]);

        // Serialized items are always qty 1; otherwise total quantity cannot decrease
        if (
            !$request->filled('item_serialno')
            && $request->item_quantity < $item->item_quantity
        ) {
            return redirect()->back()->with('error', "Cannot decrease total quantity below current total ({$item->item_quantity}).");
        }

        // Calculate how much the total increased
        $difference = $request->item_quantity - $item->item_quantity;

        // Increment remaining stock by the difference
        $item->item_quantity_remaining += $difference;

        // Update total quantity
        $item->item_quantity = $request->item_quantity;

        // Update other fields
        $item->item_name = $request->item_name;
        $item->item_serialno = $request->item_serialno;
        $item->item_remark = $request->item_remark;

        // Update Brand if provided
        if ($request->item_brand_name) {
            $brand = ItemBrand::firstOrCreate([
                'item_brand_name' => $request->item_brand_name
            ]);
            $item->item_brand_id = $brand->item_brand_id;
        }

        // Update Unit of Measure if provided
        if ($request->item_uom_name) {
            $uom = ItemUom::firstOrCreate([
                'item_uom_name' => $request->item_uom_name
            ]);
            $item->item_uom_id = $uom->item_uom_id;
        }

        // Update quantity status
        if ($item->item_quantity_remaining == 0) {
            $item->item_quantity_status = 'Out of Stock';
        } elseif ($item->item_quantity_remaining < ($item->item_quantity * 0.2)) {
            $item->item_quantity_status = 'Low Stock';
        } else {
            $item->item_quantity_status = 'Available';
        }

        $item->save();

        return redirect()->back()->with('success', 'Item updated successfully.');
    }
    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request, $item_id)
    {
        $item = Item::findOrFail($item_id);
        $deleteQty = $request->input('delete_qty');

        // If user entered a number and it's less than the total remaining
        if (!empty($deleteQty) && is_numeric($deleteQty) && $deleteQty < $item->item_quantity_remaining) {

            $item->item_quantity -= $deleteQty;
            $item->item_quantity_remaining -= $deleteQty;

            // Recalculate status logic
            if ($item->item_quantity_remaining == 0) {
                $item->item_quantity_status = 'Out of Stock';
            } elseif ($item->item_quantity_remaining < ($item->item_quantity * 0.2)) {
                $item->item_quantity_status = 'Low Stock';
            } else {
                $item->item_quantity_status = 'Available';
            }

            $item->save();

            return response()->json([
                'success' => true,
                'deleted_entirely' => false,
                'message' => "Removed $deleteQty items from stock."
            ]);
        }

        // Otherwise, delete the entire record
        $item->delete();

        return response()->json([
            'success' => true,
            'deleted_entirely' => true,
            'message' => 'Item deleted successfully.'
        ]);
    }

    public function destroyCategory($id)
    {
        $category = ItemCategory::findOrFail($id);

        // Check if there are any items using this category
        $itemCount = Item::where('item_category_id', $id)->count();

        if ($itemCount > 0) {
            return response()->json([
                'success' => false,
                'message' => "Cannot delete category. There are still $itemCount item(s) assigned to it."
            ], 422); // 422 Unprocessable Entity
        }

        $category->delete();

        return response()->json([
            'success' => true,
            'message' => 'Category deleted successfully.'
        ]);
    }

    public function bulkDestroy(Request $request)
    {
        $ids = $request->input('ids', []);
        $selectAll = $request->input('all', false); // New flag from JS

        // 1. Logic for "Select All" (Across all pages)
        if ($selectAll) {
            $query = Item::query();

            // Apply same filters as your index page so you don't delete 
            // things the user isn't currently looking at!
            if ($request->has('category') && $request->category != '') {
                $query->where('item_category_id', $request->category);
            }
            if ($request->has('brand') && $request->brand != '') {
                $query->where('item_brand_id', $request->brand);
            }
            if ($request->has('search') && $request->search != '') {
                $query->where('item_name', 'like', '%' . $request->search . '%');
            }

            $query->delete();
            return response()->json(['success' => true, 'message' => 'All filtered items deleted.']);
        }

        // 2. Logic for "Selected Page Items"
        if (!empty($ids)) {
            Item::whereIn('item_id', $ids)->delete();
            return response()->json(['success' => true, 'message' => 'Selected items deleted successfully.']);
        }

        return response()->json(['success' => false, 'message' => 'No items selected.'], 400);
    }
    // ItemController.php

    public function checkDuplicate(Request $request)
    {
        $brand = ItemBrand::where('item_brand_name', $request->item_brand_name)->first();
        // We only find the ID if the brand actually exists
        $brandId = $brand ? $brand->item_brand_id : null;

        $exists = Item::where('item_name', $request->item_name)
            ->where('item_brand_id', $brandId)
            ->where('item_serialno', $request->item_serialno) // Match serial (null matches null)
            ->exists();

        return response()->json(['exists' => $exists]);
    }
    public function getLatestItem(Request $request)
    {
        $categoryId = $request->category_id;

        $item = Item::where('item_category_id', $categoryId)
            ->latest() // uses created_at
            ->first();

        return response()->json([
            'item_name' => $item ? $item->item_name : null
        ]);
    }
}